import { CrashPack } from '../types.js';

export function renderMarkdown(pack: CrashPack): string {
  const durationSec = (pack.durationMs / 1000).toFixed(1);
  const redactionLabel = `${pack.redactionCount} value${pack.redactionCount === 1 ? '' : 's'} redacted`;
  const header = `# crashpack · ${pack.projectName}\n_${pack.generatedAt} · collected in ${durationSec}s · ${redactionLabel}_\n`;

  const sectionBlocks: string[] = [];

  for (const section of pack.sections) {
    // Edge case: No .env -> Environment section omitted entirely
    if (section.id === 'env' && section.status === 'unavailable') {
      continue;
    }

    // Edge case: No logs provided in normal run -> omit or show unavailable if explicitly requested
    if (section.id === 'logs' && section.status === 'unavailable') {
      continue;
    }

    if (section.status === 'ok' && section.content) {
      sectionBlocks.push(`## ${section.title}\n\n${section.content}`);
    } else if (section.status === 'unavailable') {
      const reason = section.unavailableReason || 'not available';
      sectionBlocks.push(`## ${section.title}\n\n_Unavailable: ${reason}_`);
    }
  }

  const footer = `\n---\n_Generated by crashpack · Built by Poorvith. No data left this machine._\n`;

  return [header, ...sectionBlocks].join('\n\n') + footer;
}
